# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnc0cqu9Y7WzRtyxAOWCgzFMLGpqDhRP
"""

import streamlit as st
import torch
import torchvision.transforms as transforms
from PIL import Image
import requests
import io

st.title(" Real-Time Object Classification")
st.write("This app uses ResNet-18 to classify webcam images in real time.")

# Step 2: Load ImageNet class labels
@st.cache_data
def load_labels():
    url = "https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt"
    response = requests.get(url)
    return response.text.strip().split("\n")

labels = load_labels()

# Step 3: Load pretrained ResNet-18 model
model = torch.hub.load('pytorch/vision', 'resnet18', pretrained=True)
model.eval()

# Step 4: Define preprocessing
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# Step 5: Upload image (simulate webcam)
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Preprocess and batch
    input_tensor = preprocess(image)
    input_batch = input_tensor.unsqueeze(0)

    # Step 6: Predict
    with torch.no_grad():
        output = model(input_batch)
        probabilities = torch.nn.functional.softmax(output[0], dim=0)

    # Top 5 predictions
    top5_prob, top5_catid = torch.topk(probabilities, 5)
    st.subheader("Top 5 Predictions")
    for i in range(top5_prob.size(0)):
        st.write(f"{labels[top5_catid[i]]}: {top5_prob[i].item():.4f}")